name: general_image
on:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gspread-omie
jobs:
  publish-extrattus-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3    

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v3
      #   with:
      #     flavor: latest=true
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          # file: ./Dockerfile
          push: True
          tags: leorzz/docker-image:gspread-omie
          labels: ${{ steps.meta.outputs.labels }}